### ISSUE TITLE
Select by fraction should include `context_length` buffer

### ISSUE THREAD

**Issue by ajati** [IBM/tsfm#23]
https://github.com/IBM/tsfm/blob/57f476a045ae3e3194376553523bc94c10969bfb/tsfm_public/toolkit/util.py#L274

Few-shot fraction generally include `context_length` buffer, otherwise 5% few-shot for `etth1` will result in 1 train sample for 512/96 (context_len/forecast_len) usecase (and other scenarios).

This should be the modified calculation:
```
end_index = int((l - context_length) * fraction + context_length)
```

Some popular examples can be found here: https://github.com/DAMO-DI-ML/NeurIPS2023-One-Fits-All/blob/9f3875dbba9f52ee534ac0902572502746f3b29d/Few-shot_Learning/data_provider/data_loader.py#L62 and some other well-know time series repos.

**Comment by wgifford** [comment]
@ajati I started making the changes here: https://github.com/IBM/tsfm/pull/24/files

Similar to the above I first calculate the size of the selected window, such that the minimum size is guaranteed to be context_length.

selected_size = int((l - minimum_size) * fraction + minimum_size)

Then we choose that amount of data either at the beginning or end of the original training dataset. This way we are guaranteed to have a consistent size independent of the location of the data.

**Comment by wgifford** [comment]
Closing as this has been resolved.
