### ISSUE TITLE
TypeError: Object of type Timedelta is not JSON serializable

### ISSUE THREAD

**Issue by SujayC66** [IBM/tsfm#25]
Please fix the issue
tsp = TimeSeriesPreprocessor(
    timestamp_column=timestamp_column,
    id_columns=id_columns,
    target_columns=forecast_columns,
    scaling=True,
)
tsp.train(train_data)

**Comment by RoelofKuipers** [comment]
Hello, could you let me know how you fixed this?

**Comment by SujayC66** [comment]
clone the repo using !git clone https://github.com/IBM/tsfm.git
Open time_series_preprocessor.py file and add following two lines to recursive_check_ndarray method
elif isinstance(value, timedelta):
        dictionary[key] = str(value)

It worked for me
