### ISSUE TITLE
Question: What are those parameters in the ForecastDFDataset Class

### ISSUE THREAD

**Issue by gabriel301** [IBM/tsfm#43]
I am running the notebook patch_tsmixer_blog, and noticed that in the example, only the two column parameters are set in the ForecastDFDataset class constructor:

- target columns 
- timestamp column

Looking at the code, I realized that there are 4 other column parameters that are not set, but I could not find any documentation that explains what are those columns:

- observable_columns
- control_columns
- conditional_columns
- static_categorical_columns

Could anyone please explain what are those columns, and if possible, give exemples on where they are applicable to use?

Thanks in advance.

**Comment by wgifford** [comment]
Hi @gabriel301 thank you for your interest in TSFM.

Those columns specifiers are there to support different kinds of exogenous inputs and categorical features. Here are the definitions from the forecasting pipeline (I need to improve the docstrings in other functions):

```
timestamp_column (str): The name of the column containing the timestamp of the time series.

id_columns (List[str]): List of column names which identify different time series in a multi-time series input.

target_columns (List[str]): List of column names which identify the target channels in the input, these are the
    columns that will be forecasted.

observable_columns (List[str]): List of column names which identify the observable channels in the input.
    Observable channels are channels which we have knowledge about in the past and future. For example, weather
    conditions such as temperature or precipitation may be known or estimated in the future, but cannot be
    changed.

control_columns (List[str]): List of column names which identify the control channels in the input. Control
    channels are similar to observable channels, except that future values may be controlled. For example, discount
    percentage of a particular product is known and controllable in the future.

conditional_columns (List[str]): List of column names which identify the conditional channels in the input.
    Conditional channels are channels which we know in the past, but do not know in the future.

static_categorical_columns (List[str]): List of column names which identify categorical-valued channels in the input
    which are fixed over time.
```

At this time, we haven't publicly released any models which support exogenous.

**Comment by gabriel301** [comment]
Thanks @wgifford !
