### ISSUE TITLE
Code for TTMs

### ISSUE THREAD

**Issue by StatMixedML** [IBM/tsfm#7]
Your paper _TTMs: Fast Multi-level Tiny Time Mixers for Improved Zero-shot and Few-shot Forecasting of Multivariate Time Series_ 
reads very interesing. Since you mention that you plan to release the code, I would like to kindly ask if there is a timeline when to expect the code to be available.

Many thanks!

**Comment by wgifford** [comment]
@StatMixedML This effort is in progress and we are hoping to release this within a few weeks. Thanks for your interest.
